apiVersion: apps/v1
kind: Deployment
metadata:
  name: testresultservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TestResultService
  template:
    metadata:
      labels:
        app: TestResultService
    spec:
      containers:
      - name: dockersamplerepos
        image: samplecr.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: testresultservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: TestResultService
